apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      labels:
        app: kernel-controller
        kustomize.component: kernel-controller
    spec:
      containers:
        - name: manager
          image: weekenthralling/jupyter-kernel-controller:dev
          command:
            - /kernel-controller
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: service-account