apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-kernel-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernel-controller
  template:
    metadata:
      labels:
        app: kernel-controller
        kustomize.component: kernel-controller
    spec:
      containers:
        - name: manager
          image: weekenthralling/jupyter-kernel-controller:dev
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: jupyter-kernel-controller
