apiVersion: v1
kind: Service
metadata:
  labels:
    app: kernel-controller
    kustomize.component: kernel-controller
  name: jupyter-kernel-service
spec:
  ports:
    - port: 443
  selector:
    app: kernel-controller
    kustomize.component: kernel-controller
