apiVersion: v1
kind: Service
metadata:
  labels:
    app: kernel-controller
    kustomize.component: kernel-controller
  name: jupyter-kernel-service
spec:
  ports:
    - name: metrics
      port: 8080
  selector:
    app: kernel-controller
    kustomize.component: kernel-controller
