apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-kernels-admin
  labels:
    rbac.authorization.jupyter.org/aggregate-to-jupyter-admin: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.jupyter.org/aggregate-to-jupyter-kernels-admin: "true"
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-kernels-edit
  labels:
    rbac.authorization.jupyter.org/aggregate-to-jupyter-edit: "true"
    rbac.authorization.jupyter.org/aggregate-to-jupyter-kernels-admin: "true"
rules:
  - apiGroups:
      - jupyter.org
    resources:
      - kernels
      - kernels/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-kernels-view
  labels:
    rbac.authorization.jupyter.org/aggregate-to-jupyter-view: "true"
rules:
  - apiGroups:
      - jupyter.org
    resources:
      - kernels
      - kernels/status
    verbs:
      - get
      - list
      - watch
